---
# Option A: Generate self-signed cert with DNS SAN for cloud.example.local
- name: Generate self-signed key (if requested)
  when:
    - reverse_proxy == 'nginx'
    - nginx_tls_enabled | bool
    - nginx_generate_self_signed | bool
  community.crypto.openssl_privatekey:
    path: "{{ nginx_dir }}/certs/privkey.pem"
    size: 2048
    type: RSA
    mode: "0600"
    owner: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    group: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"

- name: Generate CSR for self-signed (if requested)
  when:
    - reverse_proxy == 'nginx'
    - nginx_tls_enabled | bool
    - nginx_generate_self_signed | bool
  community.crypto.openssl_csr:
    path: "{{ nginx_dir }}/certs/request.csr"
    privatekey_path: "{{ nginx_dir }}/certs/privkey.pem"
    common_name: "{{ nginx_cert_cn }}"
    subject_alt_name: "{{ nginx_cert_sans }}"
    owner: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    group: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    mode: "0644"

- name: Generate self-signed certificate (if requested)
  when:
    - reverse_proxy == 'nginx'
    - nginx_tls_enabled | bool
    - nginx_generate_self_signed | bool
  community.crypto.openssl_certificate:
    path: "{{ nginx_dir }}/certs/fullchain.pem"
    privatekey_path: "{{ nginx_dir }}/certs/privkey.pem"
    csr_path: "{{ nginx_dir }}/certs/request.csr"
    provider: selfsigned
    valid_days: 825
    owner: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    group: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    mode: "0644"

# Option B: Use provided cert files (copy into place)
- name: Copy provided fullchain.pem
  when:
    - reverse_proxy == 'nginx'
    - nginx_tls_enabled | bool
    - not nginx_generate_self_signed | bool
  ansible.builtin.copy:
    src: "{{ nginx_cert_fullchain_src }}"
    dest: "{{ nginx_dir }}/certs/fullchain.pem"
    owner: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    group: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    mode: "0644"

- name: Copy provided privkey.pem
  when:
    - reverse_proxy == 'nginx'
    - nginx_tls_enabled | bool
    - not nginx_generate_self_signed | bool
  ansible.builtin.copy:
    src: "{{ nginx_cert_privkey_src }}"
    dest: "{{ nginx_dir }}/certs/privkey.pem"
    owner: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    group: "{{ (use_service_user | bool) | ternary(service_user, 'root') }}"
    mode: "0600"
