# ----- Runtime selection -----
container_runtime: auto            # auto | docker | podman
preferred_runtime: docker
docker_compose_command: "docker compose"
podman_compose_command: "podman-compose"

# ----- Service & paths -----
service_name: nextcloud-stack
use_service_user: true
service_user: nextcloud

project_dir: "/srv/nextcloud"
compose_project_name: "nextcloud"
stack_network: "nextcloud_net"

timezone: "Australia/Sydney"

# ----- Images -----
nextcloud_image: "nextcloud:29-apache"    # Apache variant serves HTTP on :80
postgres_image: "postgres:16"
redis_image: "redis:7"
cloudflared_image: "cloudflare/cloudflared:latest"

# ----- Features -----
redis_enabled: true
cloudflared_enabled: true
reverse_proxy: nginx

# ----- Nextcloud domains/links -----
# Public via Cloudflare Tunnel:
#   cloud.example.com -> http://nextcloud:80 (container network)
# Local via NGINX (LAN):
#   cloud.example.local -> https://<LAN-IP>:443 -> nginx -> nextcloud:80
nextcloud_trusted_domains:
  - "cloud.example.com"
  - "cloud.example.local"
nextcloud_overwrite_host: "cloud.example.com"
nextcloud_overwrite_protocol: "https"
nextcloud_overwrite_cli_url: "https://cloud.example.com"

# Proxies we trust for X-Forwarded-* (tune for your networks)
trusted_proxies_cidrs:
  - "172.16.0.0/12"
  - "192.168.0.0/16"

# ----- Paths for volumes -----
nc_app_dir: "{{ project_dir }}/nextcloud/app"
nc_data_dir: "{{ project_dir }}/nextcloud/data"
pg_data_dir: "{{ project_dir }}/postgres"

# ----- NGINX (local private entrypoint) -----
nginx_image: "nginx:1.27-alpine"
nginx_dir: "{{ project_dir }}/nginx"
nginx_tls_enabled: true
nginx_bind_ip: "0.0.0.0"       # or "192.168.0.1" to bind only on that IP
nginx_https_port: 443
nginx_http_port: 80            # will 301 redirect to HTTPS

# TLS certificate options:
# A) Generate self-signed cert for cloud.example.local
nginx_generate_self_signed: true
nginx_cert_cn: "cloud.example.local"
nginx_cert_sans:
  - "DNS:cloud.example.local"

# B) If you have real certs, disable generation and point to your files:
# nginx_generate_self_signed: false
# nginx_cert_fullchain_src: "/path/to/fullchain.pem"
# nginx_cert_privkey_src:   "/path/to/privkey.pem"
